version: '3.8'
services:
  db:
    image: postgres:13.2
    ports:
      - 5449:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: weatherman
    volumes:
      - db-data:/var/lib/postgresql/data:rw
  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/weatherman:delegated
    links:
      - db
    environment:
      DATABASE_URL: "postgresql://root:root@db:5432/weatherman"
      APP_URL: "http://weatherman.local:8099"
      APP_ENV: "dev"
      APP_SECRET: "2ce9f2327fbe8ac3a9323ca51df3ffff"
      APP_HOSTNAME: "weatherman.local"
      MESSENGER_TRANSPORT_DSN: "doctrine://default?auto_setup=0"
      GOOGLE_MAPS_API_KEY: "AIzaSyAHaWOMt8h1VxyjPCXXEStGnBmLbfAMduc"
      OPEN_WEATHER_MAP_API_KEY: "2782634eed1c90284914691197d5acc4"
  nginx:
    image: nginx:1.19
    ports:
      - "8099:80"
    volumes:
      - .:/var/www/weatherman:delegated
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
volumes:
  db-data: